config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  root 'posts#index'
  get '/about', to: 'static_pages#about'
  resources :users, only: [:show, :index]

  resources :posts do
    resources :comments
  end

  get '/explore', to: 'posts#all'
  get '/friends', to: 'friendships#index'
  get '/requests', to: 'friendships#pending'

  resources :likes, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy, :update]

end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :likes, as: :likeable, dependent: :destroy

    validates :user_id, presence: true
    validates :body, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  require 'will_paginate/array'

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where("user_id IN (?) OR user_id = ?", current_user.confirmed_friends_ids, current_user.id).order('updated_at DESC').paginate(page: params[:page], per_page: 10)
  end

  def all
    #@posts = Post.all.order('updated_at DESC')
    @posts = Post.paginate(page: params[:page], per_page: 10).order('updated_at DESC')
  end
  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create

    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to :root, notice: 'Post was successfully created.'
    else
      render 'new'
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @post.update_attributes(post_params)
      flash[:success] = "Post was successfully updated."
      redirect_to post_url(@post)
    else
      render 'edit'
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
      @post.destroy
      flash[:success] = "Post deleted"
      redirect_to posts_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def correct_user
      redirect_to :root, notice: 'Not your post!' if @post.user_id != current_user.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_feed_item.html.erb
<% posts.each do |post| %>
  <div class="post">
    <div class="user_info">
      <p><%= gravatar_for post.user, size = 30 %>
      <em><%= link_to post.user.name, post.user%></em></p>
      <p><%= render "friendships/friend_request_only", user: post.user %></p>
      <p><%= post.updated_at.to_s(:short) %></p>
    </div>
    <div class="post_body">
      <p><%= post.body %></p>
      <%= render 'like_post', post: post %>
      <p><%= link_to "Comments (#{post.comments.count})", post %></p>
      <% if post.user_id == current_user.id %>
        <%= link_to 'Edit', edit_post_path(post), class: "editable" %>
        <%= link_to 'Delete post', post, method: :delete, data: { confirm: 'Are you sure?' } , class: "editable"%>
      <% end %>
    </div>

  </div>
<% end %>
<%= will_paginate posts %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, class: "edit_user") do |form| %>
  <%= form.label :body %> <br>
  <%= form.text_area :body %> <br> <br>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit class: "btn btn-sm btn-success"  %>
  </div>
  <%= link_to 'Back', posts_path %>
<% end %>

app/views/posts/_friend_request_only.erb
<% confirmed_friend = current_user.confirmed_friends.find { |friend| friend.id == user.id} %>
<% pending_friendship = current_user.pending_friendships.find { |f| f.recipient_id == user.id } %>
<% pending_invite = current_user.pending_invites.find { |invite| invite.creator_id == user.id } %>

<% if user != current_user && !pending_friendship && !pending_invite && !confirmed_friend %>

  <%= form_for(current_user.friendships.build, url: friendships_path) do |f| %>
    <%= f.hidden_field :recipient_id, value: user.id %>
    <%= f.submit "Add friend" %>
  <% end %>

<% elsif pending_invite %>

    <%= button_to 'Accept friendship', pending_invite, method: :put %>

<% end %>

app/views/posts/_like_comment.html.erb
<% pre_like = comment.likes.find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
  <%= form_for(pre_like, url: like_path(pre_like.id), method: :delete) do |f| %>

    <%= f.hidden_field :likeable_id, value: comment.id %>
    <%= f.hidden_field :likeable_type, value: "Comment" %>

    <%= hidden_field_tag :post_id, params[:id] %>
    <%= f.submit "Unlike (#{comment.likes.count})", class: "btn btn-warning btn-sm" %>
  <% end %>
<% else %>
  <%= form_for(comment.likes.build, url: likes_path) do |f| %>

    <%= f.hidden_field :likeable_id, value: comment.id %>
    <%= f.hidden_field :likeable_type, value: "Comment" %>

    <%= hidden_field_tag :post_id, params[:id] %>
    <%= f.submit "Like (#{comment.likes.count})", class: "btn btn-primary btn-sm" %>
  <% end %>
<% end %>

app/views/posts/_like_post.html.erb
<% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
  <%= form_for(pre_like, url: like_path(pre_like.id), method: :delete) do |f| %>

    <%= f.hidden_field :likeable_id, value: post.id %>
    <%= f.hidden_field :likeable_type, value: "Post" %>
    <%= f.submit "Unlike (#{post.likes.count})", class: "btn btn-warning btn-sm"%>
  <% end %>

<% else %>
  <%= form_for(post.likes.build, url: likes_path) do |f| %>

    <%= f.hidden_field :likeable_id, value: post.id %>
    <%= f.hidden_field :likeable_type, value: "Post" %>
    <%= f.submit "Like (#{post.likes.count})" , class: "btn btn-primary btn-sm" %>
  <% end %>
<% end %>

app/views/posts/all.html.erb
<p class='new_post'><%= link_to 'New Post', new_post_path , class: 'btn btn-lg btn-dark'%></p>
<%= render 'feed_item', posts: @posts %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p class='new_post'><%= link_to 'New Post', new_post_path , class: 'btn btn-lg btn-dark'%></p>

<%= render 'feed_item', posts: @posts %>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="show">
  <p><%= @post.body %></p>
  <p><%= gravatar_for @post.user, size = 30 %>
  <em><%= link_to @post.user.name, @post.user%></em></p>
  <p><%= render "friendships/friend_request_only", user: @post.user %></p>
  <p>Last updated: <%= @post.updated_at.to_s(:short) %></p>


  <% if @post.user_id == current_user.id %>
    <%= link_to 'Edit', edit_post_path(@post), class: "editable" %>
    <%= link_to 'Delete post', @post, method: :delete, data: { confirm: 'Are you sure?' } , class: "editable"%>
  <% end %>

</div>
<div class="show second">

<h4>Comments</h4>

<%= form_with(model: @comment, url: post_comments_path(@post), local: true) do |form| %>

    <%= form.text_area :body ,cols: 50, rows: 5%> <br> <br>

    <%= hidden_field_tag :id, @post.id %>

    <div class="actions">
      <%= form.submit class: "btn btn-sm btn-success" %>
    </div>
  <% end %>

<% @post.comments.order('updated_at DESC').each do |comment| %>
  <% unless comment.id.nil? %>
    <div class="comment">
      <p><%= comment.body %></p>
      <p>- <em><%= link_to comment.user.name, comment.user%></em></p>

      <%= render 'like_comment', comment: comment %>

      <% if comment.user_id == current_user.id %>
      <p class="vert-space"><%= link_to 'Delete comment', post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
    </div>
    <% end %>
  <% end %>
<% end %>


</div>