config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  root 'posts#index'
  get '/about', to: 'static_pages#about'
  resources :users, only: [:show, :index]

  resources :posts do
    resources :comments
  end

  get '/explore', to: 'posts#all'
  get '/friends', to: 'friendships#index'
  get '/requests', to: 'friendships#pending'

  resources :likes, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy, :update]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FaceApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



    <header>
      <div class="container">
        <nav>
          
          <% if user_signed_in? %>
            <%= link_to "Feed", root_path, class: cp(root_path)%>
            <%= link_to 'Explore', explore_path, class: cp(explore_path) %>
            <%= link_to 'Friends', friends_path, class: cp(friends_path) %>
            <%= link_to 'All users', users_path, class: cp(users_path) %>
            <% count = current_user.pending_invites.count%>
            <%= link_to 'Friend Requests (' + count.to_s + ')', requests_path, class: cp(requests_path) %>
            <div class="right">
              <%= link_to 'Edit profile', edit_user_registration_path, class: cp(edit_user_registration_path) %>
              <%= link_to "Logout (" + current_user.email + ")", destroy_user_session_path, method: :delete  %>
            </div>

          <% else %>
            <%= link_to "Sign up", new_user_registration_path, class: cp(new_user_registration_path)  %>
            <%= link_to "Login", new_user_session_path, class: cp(new_user_session_path)  %>
          <% end %>

        </nav>
      </div>
    </header>



    <main class="container <%= controller_name %>">

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>